### PR TITLE
Adding the french translation for the software

### PR DESCRIPTION
**Pull request by XIAA25**
Translated the software to french
Feel free to contact me for any comment on the translation

Guillaume Lameyse 
<guillaumelameyse@gmail.com>

### CODE REVIEW

**Comment by XIAA25** [comment]
I also just commited the Dutch translation for the software

**Comment by filecxx** [comment]
Thanks for your contribution.
If you need anything, please let me know.

**Comment by XIAA25** [comment]
No problem, I'm happy I could help.
I was motivated to contribute for the lifetime activation code hahaha.
So I hope I could get my hands on one if it the offer is still available.

**Comment by filecxx** [comment]
Of course, please provide your software UID or username from w.filecxx.com

**Comment by XIAA25** [comment]
Thank you, I'm so happy, the tool you made is so nicie! I'll use it so much!
Here my username on your website: XIAA
Thank you so much

**Comment by XIAA25** [comment]
Activated!
Thank you so so much!

**Comment by filecxx** [comment]
anytime

**Pull request merged**
