### PR TITLE
Create ru_RU.lang

### PR DESCRIPTION
**Pull request by vanja-san**

### CODE REVIEW

**Comment by vanja-san** [comment]
I'm already working on a full translation of the program 👍

**Comment by filecxx** [comment]
Great, thank you.+1

**Comment by vanja-san** [comment]
@filecxx Can I replace old translation file with a new one?

**Comment by filecxx** [comment]
> @filecxx Can I replace old translation file with a new one? In old file translation for site, in new file translation for program. Old File: 70 strings New File: 561 strings

software lang files are different from website lang files.
software lang files should be put into bin/lang/ directory, the path should be bin/lang/ru_RU.lang

**Comment by filecxx** [comment]
Don't forget to backup changed files from the software directory, because existing files will be replaced during the software update process.

**Comment by vanja-san** [comment]
@filecxx I meant here, if I edit local file and replace it with a new one!

**Comment by filecxx** [comment]
Sure, why not.

**Pull request merged**
