### PR TITLE
Add id_ID (Indonesian) language for website

### PR DESCRIPTION
**Pull request by cyberzilla**
i just translate en_US.lang to id_ID.lang

### CODE REVIEW

**Comment by filecxx** [comment]
Thank you very much.

**Comment by cyberzilla** [comment]
> Thank you very much.

how to get activation code brother? i just using this method

Screenshot 2024-11-04 172421

[activate](https://filecxx.com/en_US/activation_code.html)

**Comment by filecxx** [comment]
What is your username from the dashboard?

**Comment by cyberzilla** [comment]
> What is your username from the dashboard?
> 
> https://w.filecxx.com/

username: cyberzilla

**Comment by filecxx** [comment]
Please login and check out.

**Comment by cyberzilla** [comment]
> Please login and check out.

thanks brother

**Pull request merged**
