### PR TITLE
Turkish translation just arrived!

### PR DESCRIPTION
**Pull request by geeede**
Firstly, thanks for the this awesome software.
I just completed the Turkish translation.
It's my first contribution to an open source project so if something is wrong please contact me.

### CODE REVIEW

**Comment by filecxx** [comment]
Thanks for your contribution.

**Comment by geeede** [comment]
> Thanks for your contribution.

You're welcome. I'm happy that I could help.
If it's possible could I get a lifetime activation code?
Recently the software has been giving constant alerts for a while now :)

**Comment by filecxx** [comment]
Of course, it's at least I can do.

Please provide me with your w.filecxx.com username.

**Comment by geeede** [comment]
> 

Yeah sure, it's geeede.
Thank you so much

**Comment by filecxx** [comment]
anytime.

**Pull request merged**
